name: Build

on:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup qemu
      run: |
        sudo apt update
        sudo apt -y install qemu-kvm expect
    - name: Install plan9 binaries from the latest release
      run: |
        gh release download --pattern=x86.tar.gz
        tar zxf x86.tar.gz
        rm -f x86.tar.gz
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Run tests
      run: |
        ./boot/mkdirs
        ./.github/workflows/build.tcl
