name: Build

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - run: |
        sudo apt update
        sudo apt -y install qemu-kvm expect

        gh release download --pattern=x86.tar.gz
        tar zxf x86.tar.gz
        rm -f x86.tar.gz
        ./.github/workflows/build.tcl
      env:
        GH_TOKEN: ${{ github.token }}
